frequency: 50
sensor_timeout: 1.0
publish_tf: true
publish_acceleration: false
base_link_frame: rmui
# imu
imu0: /rmui/rmui_node/output/imu
imu0_config: [true, true, true,
              true, true, true,
              true, true, true,
              true, true, true,
              true, true, true]
imu0_nodelay: true
imu0_differential: true
imu0_remove_gravitational_acceleration: true
