frequency: 50
sensor_timeout: 1.0
publish_tf: true
publish_acceleration: false
odom_frame: rmui2_world
world_frame: rmui2_world
base_link_frame: rmui2_link
# imu
imu0: /rmui2/rmui_node/output/imu_calibrated
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_nodelay: true
imu0_differential: false
imu0_remove_gravitational_acceleration: true
